### ISSUE TITLE
Task specific interfaces

### ISSUE THREAD

**Issue by condesales** [algolia/algoliasearch-client-android#10]
Any chance of splitting the [IndexListener](https://github.com/algolia/algoliasearch-client-android/blob/master/src/main/java/com/algolia/search/saas/IndexListener.java) in several smaller interfaces?

This one has too many methods. Let's say we just want to use the search bit of Algolia, why would I have to implement ?
```@Override
    public void addObjectsResult(Index index, JSONArray jsonArray, JSONObject jsonObject) {

    }
```

**Comment by redox** [comment]
Yeah, I think you're right. What about extracting all search/get methods? I assume you're only doing search with the Android client? @condesales

**Comment by condesales** [comment]
That would work for search. But why search only?
You probably need to split all (Result + Error) to each one of the cases user may perform a request to Algolia. I don't know, you can judge better as you know your service better than I do.
This way you would cover all possibilities. If you do this for one, shouldn't be hard to do it for all.

**Comment by redox** [comment]
> But why search only?

Sure sure, we can do it for all. The thing is, I don't think a lot of users are actually triggering indexing from their Android app (I hope so actually, could be a big security issue if the key leaks); so it was just to confirm that you're only doing search.

**Comment by condesales** [comment]
Yep. For my app needs, just search.

**Comment by dethi** [comment]
@redox do you have a idea of how we can handle the change without breaking the compatibility?
Or should we break compatibility because #11 will certainly break it too.
