### ISSUE TITLE
Do not have `app_name` string resource embedded

### ISSUE THREAD

**Issue by yukuku** [algolia/algoliasearch-client-android#104]
<string name="app_name">algoliasearch</string>

is embedded in the library's `values.xml`. If the app does not override it and user is not aware of it and using `R.string.app_name` thinking that it is the application name, `algoliasearch` is shown. 

I think it should be removed.

**Comment by PLNech** [comment]
Hey @yukuku, thank you for your contribution !
Good catch, there is no reason to ship an `app_name` here.

As Travis won't expose Secure Environment Variables to a foreign PR, I closed #105 and reopened it as #106 from our repository ;)

**Comment by PLNech** [comment]
Fixed in 7cf4e9c, waiting for release.

**Comment by PLNech** [comment]
Released in [3.3.0](https://github.com/algolia/algoliasearch-client-android/releases/tag/3.3.0).
