### ISSUE TITLE
Respond Client request using onPostExecute

### ISSUE THREAD

**Issue by condesales** [algolia/algoliasearch-client-android#11]
if you move this [_sendRequest](https://github.com/algolia/algoliasearch-client-android/blob/master/src/main/java/com/algolia/search/saas/APIClient.java#L411) call to the onPostExecute method from the AsyncTask, the results will be received on the Main Application Thread and so we can safely update the UI as need.

**Comment by condesales** [comment]
Also, read the [AsyncTask](http://developer.android.com/reference/android/os/AsyncTask.html) documentation. Your implementation is completely wrong.

**Comment by redox** [comment]
Thank you for reporting us that @condesales; I'll ask our Android developers to have a look. Feel free to submit a PR if you know how to fix it.

**Comment by redox** [comment]
Hey @condesales, we've been working hard on improving our Android library and we're close to release a v2. I've just published a v2.1.0 on Maven Central, do you mind giving it a try and let you know what you think about it?
