### ISSUE TITLE
Fix inconsistent nullability of query

### ISSUE THREAD

**Issue by clement-leprovost** [algolia/algoliasearch-client-android#130]
In [Index.searchAsync()](https://github.com/algolia/algoliasearch-client-android/blob/master/algoliasearch/src/main/java/com/algolia/search/saas/Index.java#L110-L114), the `query` argument is declared as `@NonNull` in the code, but advertised as nullable in the comment.

- Fix this inconsistency.
- Review all other similar parameters, as other inconsistencies may exist.

**Comment by PLNech** [comment]
Fixed in #132.
