### ISSUE TITLE
Disjunctive OR operation for facet & facet Filter

### ISSUE THREAD

**Issue by sunit09** [algolia/algoliasearch-client-android#15]
How to add multiple facets and facet Filters with AND/OR relations from android?

**Comment by clement-leprovost-algolia** [comment]
@sunit09 I think what you are looking for is the `Index.searchDisjunctiveFacetingAsync()` method.

**Comment by sunit09** [comment]
Is it applicable for Android?

**Comment by clement-leprovost-algolia** [comment]
Well, this *is* the Android client.

**Comment by sunit09** [comment]
1 more thing, setFacetFilters(List<String>) accepts only List of Strings, then How can I add multiple OR operated filters?

**Comment by clement-leprovost-algolia** [comment]
For questions related to using the search engine, may I redirect you to our [Support Center](https://www.algolia.com/support)? You will find better reactivity there.

Issues in GitHub are primarily intended for bugs and feature requests.

Best regards,
