### ISSUE TITLE
Disjunctive Faceting in android

### ISSUE THREAD

**Issue by sohamchak** [algolia/algoliasearch-client-android#16]
Hi I am php developer. I have worked in algolia instant search where I used disjunctive faceting in many cases. Now android team is making the app of search part. But Disjunctive Faceting in android is not implemented in the doc yet. Please help me regarding how to implement Disjunctive Faceting in Android or how I can help the android team to perform disjunctive faceting

**Comment by clement-leprovost-algolia** [comment]
We should definitely update the documentation. Tagged the issue as such.

@sohamchak The `Index.searchDisjunctiveFacetingAsync()` should work the same way as the `searchDisjunctiveFaceting()` function in the PHP client.

**Comment by PLNech** [comment]
@sohamchak The documentation has been updated to include [instructions for disjunctive faceting on Android](https://www.algolia.com/doc/android#disjunctive-faceting).
