### ISSUE TITLE
Could not find any version that matches com.algolia:algoliasearch-android:3.+.

### ISSUE THREAD

**Issue by paulokhouri** [algolia/algoliasearch-client-android#161]
I inserted the lib like was in site:
`compile 'com.algolia:algoliasearch-android:3.+@aar'`

But I got this error:
```
Error:Could not find any version that matches com.algolia:algoliasearch-android:3.+.
<a href="searchInBuildFiles">Search in build.gradle files</a>
```

What is the real path to compile it?

**Comment by PLNech** [comment]
Hi @paulokhouri, thank you for reporting this issue.
The documentation you mentioned is outdated, you should use this instead:

```groovy
    compile 'com.algolia:algoliasearch-android:3.5'
```

I will update the documentation accordingly!

**Comment by paulokhouri** [comment]
Thanx!!
