### ISSUE TITLE
Browse All Index Content

### ISSUE THREAD

**Issue by mtaweel** [algolia/algoliasearch-client-android#18]
How can I call the following REST API using the Android client?
https://www.algolia.com/doc/rest#browse-all-index-content

**Comment by clement-leprovost-algolia** [comment]
Browsing an index is not (yet) supported on the Android client, because it is usually more of a "back-end" operation; we did not think it was needed on the mobile side.

@mtaweel I would be interested in knowing your use case for this method.

Note: Tagging this issue as "enhancement" as it is basically a feature request.

**Comment by mtaweel** [comment]
We are using Algolia to retrieve list of all hotels in a city in realtime which might exceed the 1,000 limit of the "Search" API for some big cities. We are allowing the user to scroll the list but when we request the pages after the 1,000 limit nothing is being returned as stated here https://www.algolia.com/doc/faq/index-configuration/how-can-i-retrieve-all-the-records-in-my-index

**P.S. **The above FAQ needs to be corrected, because it says all clients do support "Browse API", and that is not the case with the current Android Client.

However, we were able to overcome this by using the "Browse" API in our Web App as you can see [here](https://www.yamsafer.com/en/search?attraction_id=15973&attraction_type=city&checkin_date=2016-02-29&checkout_date=2016-03-01) 
and we were going for the same implementation in both our Android and iOS Apps, but the Android client doesn't support it yet as you stated.

So @clement-leprovost-algolia, when do you think this will be supported for the Android Client?

**Comment by clement-leprovost-algolia** [comment]
I think it's definitely worth considering adding this feature (and not only because our FAQ says so! ^_^), since it's a way to perform "infinite scrolling" and the iOS clients support it.

@mtaweel No ETA at this stage. We'll update this issue when we have a roadmap.

**Comment by clement-leprovost-algolia** [comment]
Available in the `v3` branch, waiting for release.

**Comment by mtaweel** [comment]
Great! Thx
