### ISSUE TITLE
Confusing documentation between `filters` and `setFilters` operators

### ISSUE THREAD

**Issue by aseure** [algolia/algoliasearch-client-android#187]
A customer pointed out the documentation is not clear enough between `filters` [1] which accepts `:` and `setFilters` [2] which accept comparison operators. This issue may be reported higher than this API client.

[1] https://www.algolia.com/doc/api-client/android/parameters#filters
[2] https://www.algolia.com/doc/guides/search/filtering-faceting#filter-by-numerical-value

**Comment by maxiloc** [comment]
I also find it confusing, we can rewrite the section but I think it's a discussion to have to allow = even for facets

**Comment by PLNech** [comment]
@maxiloc: How should we address this with the new documentation? 🙂

**Comment by PLNech** [comment]
@maxiloc: Any update on this topic? I can also close this and reopen it on the doc repo as it belongs more there.

**Comment by maxiloc** [comment]
I don't think the issue is relevant anymore, we don't document setFilter, no ?

**Comment by PLNech** [comment]
Indeed. 👌
