### ISSUE TITLE
attributes or attributesToRetrieve?

### ISSUE THREAD

**Issue by kokliKo** [algolia/algoliasearch-client-android#19]
On this line, should we use attributes or attributesToRetrieve?
https://github.com/algolia/algoliasearch-client-android/blob/963afeebf51661f4b34c871cefe15397d133972e/algoliasearch/src/main/java/com/algolia/search/saas/Query.java#L794

**Comment by clement-leprovost-algolia** [comment]
`attributes` and `attributesToRetrieve` have the same semantics, however the former is deprecated. So we definitely should switch to the latter. Good catch.

**Comment by clement-leprovost-algolia** [comment]
Implemented in the `v3` branch, waiting for release.
