### ISSUE TITLE
Issue with using Algolia library on gradle

### ISSUE THREAD

**Issue by otnateos** [algolia/algoliasearch-client-android#20]
Hi there,

I'm having trouble trying to use Algolia search client library during debug manifest merger because Algolia library specify `allowBackup=true` property in the manifest, so we can't use it if our application specify `allowBackup=false` in our application manifest.

**Exception:**
```
...../app/src/main/AndroidManifest.xml:11:7-34 Error:
	Attribute application@allowBackup value=(false) from AndroidManifest.xml:11:7-34
	is also present at [com.algolia:algoliasearch-android:2.5.0] AndroidManifest.xml:36:9-35 value=(true).
	Suggestion: add 'tools:replace="android:allowBackup"' to <application> element at AndroidManifest.xml:9:3-111:17 to override.
```

I have tried the suggested action to take above but still Gradle won't let it merge. I have tested using latest version, 2.4.0, and 2.3.0 (which I believe the rest will fail as well) and even tweak our Android Gradle plugin to 1.5.0 (we use 1.2.3). I even removed our build flavor to test the issue, but none of my approach works.

**Question:**

1. Is there specific reason that you specify the `allowBackup=true` in your library? It seems quite strange since not many libraries doing that.
2. Is there a known fix to the issue?

Thanks

**Comment by dethi** [comment]
Hi @otnateos, 
I look git log, and the option is set to true because Android Studio sets it to true by default. 
I will change it right now!

**Comment by RobertoIDL** [comment]
How can I get this version?

If I try this:

How do I get this version?

If I try to get the library like this:

compile 'com.algolia:algoliasearch-android:2.+@aar'

I'm getting an older version that still has the issue when merging the manifest. 

Thanks.

**Comment by clement-leprovost-algolia** [comment]
@RobertoIDL  Version 2.6.2 should solve this issue. Which version are you using?

**Comment by RobertoIDL** [comment]
I'm trying to use that one but using the compile url from my previous method I'm getting version 2.5.0 from the repository. 

How can I force it to get 2.6.2? I've tried using this:

compile 'com.algolia:algoliasearch-android:2.6.2'

But then I get an error about the library referencing a JAR or something like that. I know that's why we use @aar

**Comment by PLNech** [comment]
Have you tried using `compile 'com.algolia:algoliasearch-android:2.6.2@aar'`? I was able to build a functional version of algolia/algolia-android-demo successfully.

**Comment by RobertoIDL** [comment]
Thanks both @PLNech  @clement-leprovost-algolia I'm not sure what I typed as I thought I tried exactly that. 

I've just got 2.6.2 and the only error showing is due to the attribute "label" which it's fine I know how to solve that. Not sure if this attribute is compulsory, if not my recommendation is to remove it to avoid this problems.

Thanks again.

**Comment by clement-leprovost-algolia** [comment]
Actually the entire `application` element should be removed from a library manifest, at least as far as my understanding of the [Manifest merger](http://tools.android.com/tech-docs/new-build-system/user-guide/manifest-merger) goes. (I tried: it works.)

**Comment by PLNech** [comment]
Indeed, the `application` element is useful only to declare an `<activity[-alias]>`, `<service>`, `<receiver>`/`<provider>` or to specify linked shared libraries with `<uses-library>`. 

As long as we do none of these, we indeed have no reason to keep it!
