### ISSUE TITLE
How to use Index.search in non-async mode?

### ISSUE THREAD

**Issue by vshcryabets** [algolia/algoliasearch-client-android#21]
Just curious is it possible to use it in old style, withous async?

**Comment by dethi** [comment]
The method still exists but is now protected. I'm curious, why would you like to use it?

**Comment by vshcryabets** [comment]
I'm using this method inside android Loaders. Async methods is cool, but when you need to do series of actions (like retrieve data from server, then process them, then store to db and return android cursor to UI thread) it became painful, because you need to use some IPC's to synchronise threads.

**Comment by dethi** [comment]
Okay! All the async methods use a non-async one, so we can definitely change the visibility of these methods.
@redox @PLNech what do you think?

**Comment by PLNech** [comment]
Agreed, we can expose the `Index.search()` method, but we don't want users to think synchronous search is the default way to use an index. 
What about an explicit name regarding its synchronicity, like `Index.searchSync()`?

**Comment by clement-leprovost-algolia** [comment]
Yes, making clear that synchronous is not the recommended mode is crucial. So naming methods `*Sync()` seems like a good idea.
Another trick is worthwhile: asserting that those methods are not called from the main thread. (We must be careful not to use Java's built-in `assert` keyword, though, as it is often stripped from bytecode on Android platforms.)

**Comment by dethi** [comment]
@clement-leprovost-algolia it's not necessary. Android doesn't allow network calls on the main thread. It will automatically crash the app!

**Comment by clement-leprovost-algolia** [comment]
Oh yes, right, I forgot about that... :)

**Comment by PLNech** [comment]
@vshcryabets : With version [2.6.4](https://github.com/algolia/algoliasearch-client-android/releases/tag/2.6.4) and the next ones, you can now use `Index.searchSync()`.

**Comment by vshcryabets** [comment]
Thanks a lot :)
