### ISSUE TITLE
How do I download latest snapshot from master branch

### ISSUE THREAD

**Issue by otnateos** [algolia/algoliasearch-client-android#23]
How do I download the latest snapshot of master branch directly from github? I'm trying to get changes for https://github.com/algolia/algoliasearch-client-android/issues/20 and try to avoid checking out and compile the library manually.

I saw the dist directory and the latest build is not there and I tried to download using Jitpack.io but it keep giving me
```Received status code 401 from server: Repo not found or no access token provided```

**Comment by dethi** [comment]
Let's just ask @redox to release a new minor version :)

**Comment by PLNech** [comment]
Released as [2.6.1](https://github.com/algolia/algoliasearch-client-android/releases/tag/2.6.1) :)
