### ISSUE TITLE
FW: ConcurrentModificationException in Client.java

### ISSUE THREAD

**Issue by bobylito** [algolia/algoliasearch-client-android#230]
@PrabithaK reported an [issue in the JS-Helper ](https://github.com/algolia/algoliasearch-helper-js/issues/454) but it doesn't look like an issue from the JS Helper. It happened that this was related to the android client (not the [java one](https://github.com/algolia/algoliasearch-client-java/issues/166)).

**Comment by PLNech** [comment]
Stacktrace from [Issue #166 on algoliasearch-client-java](https://github.com/algolia/algoliasearch-client-java/issues/166#issuecomment-269314676): 

```java
Caused by java.util.ConcurrentModificationException
java.util.ArrayList$ArrayListIterator.next (ArrayList.java:573)
com.algolia.search.saas.Client.multipleQueries (Client.java:362)
com.algolia.search.saas.Client$5.run (Client.java:270)
com.algolia.search.saas.AbstractClient$AsyncTaskRequest$1.doInBackground (AbstractClient.java:692)
com.algolia.search.saas.AbstractClient$AsyncTaskRequest$1.doInBackground (AbstractClient.java:688)
android.os.AsyncTask$2.call (AsyncTask.java:288)
java.lang.Thread.run (Thread.java:818)
```

**Comment by PLNech** [comment]
@PrabithaK, thank you for reporting this issue!

An `ArrayList` will throw a [ConcurrentModificationException](https://docs.oracle.com/javase/7/docs/api/java/util/ConcurrentModificationException.html) if you try to modify its content while iterating on it, see the [documentation's section on iterators](https://developer.android.com/reference/java/util/ArrayList.html#fail-fast):

> The iterators returned by this class's `iterator` and `listIterator` methods are **fail-fast**: if the list is **structurally modified** at **any time after the iterator is created**, in any way **except through the iterator's own `remove` or `add` methods**, the iterator will throw a **ConcurrentModificationException**. 

When calling `Client#multipleQueries`, we iterate on `queries` and post a request for each one ; modifying the queries at the same time is thus forbidden.

@PrabithaK, can you check in your code what is modifying the `queries` after you call `multipleQueries`?

**Comment by PLNech** [comment]
@PrabithaK, thank you for reporting this issue!

An `ArrayList` will throw a [ConcurrentModificationException](https://docs.oracle.com/javase/7/docs/api/java/util/ConcurrentModificationException.html) if you try to modify its content while iterating on it, see the [documentation's section on iterators](https://developer.android.com/reference/java/util/ArrayList.html#fail-fast):

> The iterators returned by this class's `iterator` and `listIterator` methods are **fail-fast**: if the list is **structurally modified** at **any time after the iterator is created**, in any way **except through the iterator's own `remove` or `add` methods**, the iterator will throw a **ConcurrentModificationException**. 

When calling `Client#multipleQueries`, we iterate on `queries` and post a request for each one ; modifying the queries at the same time is thus forbidden.

@PrabithaK, can you check in your code what is modifying the `queries` after you call `multipleQueries`?

**Comment by PrabithaK** [comment]
I have declared the List (queries) globally and this is cleared before calling the multipleQueries on changing the input in Search. multipleSearch is called everytime when user enters something.

Please suggest some soln.

**Comment by PLNech** [comment]
The list that you pass to `multipleQueries` should not be modified between the call to `multipleQueries` and its return. As you tell me you declared this `List` globally, it is likely that you update it **before the end of a call to `multipleQueries`**: I suggest you to **modify the queries before** the call to `multipleQueries` or **after**, but **not during**. 

If you cannot avoid modifying this list while the method executes, I advise you to call multipleQueries with a *copy of the original `List`*:
```java
client.multipleQueries(new ArrayList<>(queries), strategy);
```
