### ISSUE TITLE
SSLException during the request retry

### ISSUE THREAD

**Issue by vshcryabets** [algolia/algoliasearch-client-android#24]
I've noted that there is SSLException happens when first host is unavailable.
Algolia library uses 4 hosts:

7KJECL120U-dsn.algolia.net
7KJECL120U-1.algolianet.com
7KJECL120U-2.algolianet.com
7KJECL120U-3.algolianet.com

But when library are trying to use last 3 hosts, it got:
`javax.net.ssl.SSLException: hostname in certificate didn't match: <7KJECL120U-1.algolianet.com> != <*.algolia.io> OR <*.algolia.net>`

Is it ok?

**Comment by dethi** [comment]
Should happen. Old certificate @redox ?

**Comment by redox** [comment]
> Shouldn't happen. Old certificate @redox ?

Smells SNI /o\

**Comment by PLNech** [comment]
What version of the API client are you using, and on which version of Android?

**Comment by vshcryabets** [comment]
API client version 2.6.2, Android 5.1.1

**Comment by clement-leprovost-algolia** [comment]
Version 2.6.3 (recently released) fixes this issue.
