### ISSUE TITLE
Having a common core for android & Java

### ISSUE THREAD

**Issue by ElPicador** [algolia/algoliasearch-client-android#36]
I understood you want to have a `v3` for the Android Client.
We also wanted to have a `v2` for the Java Client (1.8 & stuff like that).

Maybe we could have a common core, targeting java 1.7, as common base for new versions of the android & java client. Less code, less bugs :smile: 

WDYT?

**Comment by ElPicador** [comment]
cc: @redox, @Nagriar, @clement-leprovost-algolia, @PLNech

**Comment by clement-leprovost-algolia** [comment]
AFAIK:
- Java 8 is not supported on Android.
- Java 7 is supported, but only targeting API level 19 (Android 4.4) and above (though it seems to be only for the "try with resources" feature).

So if we want to target earlier versions of Android, I think it is safer to stick with Java 6. Sad but true.

NOTE: It find it hard to get definitive information on that topic. If someone has pointers, please share them.

**Comment by ElPicador** [comment]
Even if the core is in Java 6, the Java client would warp it for Java 1.8.

If I understand correctly the android-client will have an async API, as the Java 1.8, but with a complete different APIs (callbacks vs Future).

But what do you think of the idea of having a common core?

**Comment by PLNech** [comment]
Regarding Java 8, it seems one can use some features on an Android project with [RetroLambda](https://github.com/orfjackal/retrolambda). We can investigate the current [limitations](https://github.com/orfjackal/retrolambda#known-limitations) to see if it is really possible to use Java 8 for a common core!

**Comment by ElPicador** [comment]
Ok, it seems it's too difficult to share some code between Java & Android.

So I'm closing this one. Bye bye
