### ISSUE TITLE
Support the "get object" endpoint for Places

### ISSUE THREAD

**Issue by clement-leprovost** [algolia/algoliasearch-client-android#389]
See [REST API documentation](https://community.algolia.com/places/rest.html#get-by-objectid).

**Note:** Better wait for #388 (per-request options) to be merged first to avoid conflicts.

**Comment by PLNech** [comment]
Implemented in 73d08fb504b8d3a259e4273402ed93a64c101cb1, we forgot to close this issue after merging https://github.com/algolia/algoliasearch-client-android/pull/414.
