### ISSUE TITLE
gradle dependency / jcenter or maven central

### ISSUE THREAD

**Issue by mg6maciej** [algolia/algoliasearch-client-android#4]
Hey,
Would it be possible for you to upload releases?
It is way convinient to use from gradle or maven based android projects.
Cheers!

**Comment by redox** [comment]
If you're looking for the jars, they are available in https://github.com/algolia/algoliasearch-client-android/tree/master/dist

**Comment by mg6maciej** [comment]
Thanks for the very fast reply. I've seen these jars and I will use them.
If you want to host them on github, it's probably better to follow maven convention, like here: https://github.com/Appboy/appboy-android-sdk/tree/gh-pages/sdk/com/appboy/android-sdk-jar, so users would not have to commit jars into their repositories, but add dependency with custom maven url.
A better alternative is probably https://bintray.com/bintray/jcenter, where you can simply upload your jars and not even have to add custom url to use dependencies in build.gradle.

**Comment by redox** [comment]
Hey @mg6maciej,

yeah we're already doing it with our vanilla Java API client (https://github.com/algolia/algoliasearch-client-java/tree/master/repository/com/algolia/algoliasearch) but definitely need to it with Android as well.

Thank you for sharing jcenter -> I was not aware of such alternative. Looks good!

**Comment by PaNaVTEC** [comment]
+1 to upload to jcenter/mavencentral the algoliasearch-client-ANDROID

**Comment by RobertoIDL** [comment]
Hi,

Any news regarding gradle support?

Thanks

**Comment by redox** [comment]
On it now, sorry for the lag :/

**Comment by redox** [comment]
@RobertoIDL @PaNaVTEC @mg6maciej Could you give a try to https://bintray.com/algolia/maven/algoliasearch-client-android/view and let me know if it's working as expected?

**Comment by redox** [comment]
Actually, not so easy; stil WIP

**Comment by RobertoIDL** [comment]
Hi @redox 

Sorry for the delay, I guess is not worth trying it yet, right?

**Comment by redox** [comment]
I'm having a hard time patching the Gradle build file to include the source+javadoc jars, any chance you know how to do it @RobertoIDL?

Right now, this is what jCenter is reporting:
```
In addition to the .aar and .pom files, your version should include a sources jar, and optionally a javadoc jar. 
```

**Comment by mg6maciej** [comment]
You may try taking it from some other opensource, e.g.: https://github.com/realm/realm-java/blob/master/realm/build.gradle

**Comment by kamoljan** [comment]
+1
