### ISSUE TITLE
Decide if this client is front-end only

### ISSUE THREAD

**Issue by PLNech** [algolia/algoliasearch-client-android#471]
This question arises from the addition of scopes (synonyms, settings, rules) to `copyIndex`.  

As this client is only for front-end implementations, it does not implement the methods to create or edit Query Rules nor Synonyms. This makes an implementation of scopes in `copyIndex` pretty much useless on its own. To quote @clement-leprovost, this client was part of the copy scopes specs "_because we have support for `copyIndex`_", which stayed in this client since we forked it from the java one. 

We could go with two routes:

1. Consider this as a strictly front-end client and deprecate/remove the methods that require indexing capable keys
2. Consider this as a full fledged api client (mentioning in its doc the [security requirements](https://www.algolia.com/doc/guides/security/best-security-practices/#api-keys-in-mobile-applications) of a front-end application with indexing capabilities, i.e. dynamically-fetched Secured API Keys with expiry time). This would mean:
    - [ ] Implementation of the Synonyms API
    - [ ] Implementation of the Query Rules API
    - [ ] Implementation of the Copy `scope` parameter
    - [ ] Overhaul of the documentation to mention security guidelines along each indexing method.

Option **1** is easier, and would be _less error-prone for most of our customers_. (I wonder how many of our users hardcode a non-search-only API Key in their app, versus following the recommendation of **generating a secured api key**, with an **expiry date**, and **fetched dynamically** from their back-end). 
But for the customers who effectively follow these recommendations, this would prevent them from using these methods in a secured way, which looks like a no-go to me (I wouldn't want to penalise secure implementations for the sake of preventing insecure ones). This seems a strong argument against removing the methods, and in a weaker way against deprecating them.

Option **2** would require a lot more work, and will need some thoughtful documentation to explicitly remember these security guidelines. But if we go down this route, we might be able to educate our less secure customers while still providing a good DX to the ones who already follow our recommendations.

**Comment by clement-leprovost** [comment]
Excellent summary @PLNech. :)

I do think however that there is a third option, which is basically to stick to the current course of action. O:) We cannot rule out indexing operations being issued from the front-end, as they *might* be used to perform some kind of personalization. (Like saving favorites.)

That said, I can't see a valid use case for editing synonyms or rules from the front-end. These are global relevance settings that are essentially static. Even if we could imagine dynamic rules being used for personalization, I would strongly recommend updating them from the back-end.

Therefore, we can keep the current (full-fledged) index copy, but ignore the scoped copy, as well as anything related to synonyms or rules.

**Comment by robertmogos** [comment]
I agree with @clement-leprovost. The question we should ask ourselves is not that if the client should be strictly front-end or not, but what would be useful for our customers in a front-end implementation.

Allowing each user to edit the synonyms and the query rules, can be dangerous, especially that those changes would impact **all** the other users. But being able to index from the client side can be crucial. Like @clement-leprovost said when saving favorites.

**Comment by robertmogos** [comment]
This being said, I don't think the `scoped index copy` whould be useful in a front-end implementation. Maybe you have a use-case in mind, but I can't find any good one.

**Comment by PLNech** [comment]
@clement-leprovost @robertmogos thanks for your comments. 
Let's go for having indexing methods but nothing related to synonyms or rules 👌
