### ISSUE TITLE
Add getters on Query class fields

### ISSUE THREAD

**Issue by jrmgx** [algolia/algoliasearch-client-android#5]
It can be sometime very convenient (without a need to subclass) to get the value of previously sat field
ie: `getHitsPerPage` same with `getTagFilter` and so on...
nb: this is possible in objective-c implementation because `@properties` are public

**Comment by redox** [comment]
I've added the getters in the 1.6.1 release. Happy coding!

**Comment by jrmgx** [comment]
too fast for me :) thx
