### ISSUE TITLE
Offline fallback timeout wrongly interpreted when using time unit

### ISSUE THREAD

**Issue by clement-leprovost** [algolia/algoliasearch-client-android#549]
### Current behavior

On a `MirroredIndex`, when setting the offline fallback timeout using `MirroredIndex.setOfflineFallbackTimeout(long, TimeUnit)`, the conversion between the specified time unit and milliseconds is [erroneous](https://github.com/algolia/algoliasearch-client-android/blob/master/algoliasearch/src/offline/java/com/algolia/search/saas/MirroredIndex.java#L815), resulting in the wrong timeout being applied.

### Expected behavior

The `TimeUnit.convert` method works the other way round.

### Proposed solution

Just switch the direction of conversion! ;)

I quickly reviewed other call to `TimeUnit.convert` in the same file ([here](https://github.com/algolia/algoliasearch-client-android/blob/master/algoliasearch/src/offline/java/com/algolia/search/saas/MirroredIndex.java#L292) and [here](https://github.com/algolia/algoliasearch-client-android/blob/master/algoliasearch/src/offline/java/com/algolia/search/saas/MirroredIndex.java#L292)) and they seem correct, but probably a scan of the full codebase would be required to hunt down any other occurrences of this bug.

### References

- (Algolia internal) Ticket 68546; please notify customer when fixed

**Comment by robertmogos** [comment]
https://github.com/algolia/algoliasearch-client-android/pull/550

**Comment by PLNech** [comment]
Released in [v3.22.14](https://github.com/algolia/algoliasearch-client-android/releases/tag/3.22.14).
