### ISSUE TITLE
v3.22.15 upgraded to a beta version of the support library

### ISSUE THREAD

**Issue by JulienArzul** [algolia/algoliasearch-client-android#556]
**Bug: What is the current behavior?**
Algolia SDK 3.22.15 uses a beta version of appcompat. 
The appcompat upgrade from 26.1.0 to 28.0.0-beta01 broke my build over the weekend.

I now either have to exclude appcompat when getting algolia (solution I opted for) or use algolia dependency with the last working version (3.22.14).

**Bug: What is the expected behavior?**
Patch version of the library should not affect the calling application/libraries. It should contain only small implementation fixes.
I also expect my dependencies to use stable versions of the common libraries. I feel like it should be my choice whether or not to upgrade to the last beta version of the support library if I want some specific feature and not be forced to it by a third-party library (unless there is a disclaimer in the doc and they really need it for a feature)

**Bug: What is the proposed solution?**
It's too late for that version but in the future, I would advocate for you to:
- not upgrade dependencies to beta version unless your versioning is also in beta
- be mindful of library upgrades => when upgrading to a major version of a dependency, your versioning should at least upgrade by a minor version

I think you should be especially careful with those things since you ask people to use "3.+" as a version in your documentation. That means that even minor versions should be really light and not affect your users.

**Comment by robertmogos** [comment]
Hi @JulienArzul.

Thank you for opening the issue. I will look into it asap.

**Comment by PLNech** [comment]
Hi @JulienArzul, thanks for reporting this and sorry for the hassle. 
You're right that we should not have shipped an update to a beta version of the support library, we should have assessed better the impact of this change. 

Considering that the latest v28 release of appcompat is still in beta, I'll downgrade this dependency to the latest stable (v27.1.1) and release as `v3.26.0`. 

I'll update you here when it is released.

**Comment by PLNech** [comment]
[Version 3.26.0](https://github.com/algolia/algoliasearch-client-android/releases/tag/3.26.0) ships a fix, downgrading appcompat to `v27.1.1`.
