### ISSUE TITLE
Pagination Support

### ISSUE THREAD

**Issue by NateWickstrom** [algolia/algoliasearch-client-android#571]
Your Android client doesn't appear to support Pagination, like you [js client](https://www.algolia.com/doc/api-reference/widgets/pagination/js/) does.  Any plan on adding this feature?

**Comment by PLNech** [comment]
Hi @NateWickstrom, thanks for reaching out.

(_First of all, there might be a slight misunderstanding: this Android API Client is similar to the [JS API Client](https://github.com/algolia/algoliasearch-client-javascript), while the [InstantSearch JS](https://github.com/algolia/instantsearch.js) project you linked to relates to [InstantSearch Android](https://github.com/algolia/instantsearch-android/). **The latter is the library we recommend to use for building Android apps with Algolia, as it is simpler to use than this API Client**_)

We don't provide a pagination widget at the moment, considering that the general UX recommendations prefer infinite scrolling on mobile interfaces. You can check our docs on [how to use Infinite Scrolling in an InstantSearch Android app](https://www.algolia.com/doc/guides/building-search-ui/resources/ui-and-ux-patterns/in-depth/infinite-scroll/android/).

**Comment by PLNech** [comment]
Closing as stale. @NateWickstrom feel free to reopen this ticket and answer my previous message if you still have this issue!
