### ISSUE TITLE
Compilation Eror

### ISSUE THREAD

**Issue by Rachel-Zrihan** [algolia/algoliasearch-client-android#580]
Hi,
the project can not get complied Because objects:
Searcher and
InstantSearch
not found.

**Comment by q-litzler** [comment]
Hello,

Please refer to this [documentation](https://www.algolia.com/doc/guides/building-search-ui/getting-started/android/) to get started with InstantSearch android.

Also, the proper repository for InstantSearch v2 is [this one](https://github.com/algolia/instantsearch-android).
