### ISSUE TITLE
Query parameter: useQueryEqualsOneAttributeInRanking

### ISSUE THREAD

**Issue by ElPicador** [algolia/algoliasearch-client-android#64]
The parameter `useQueryEqualsOneAttributeInRanking` can not be set in the Query

**Comment by clement-leprovost-algolia** [comment]
This parameter is not part of the public API. -> Won't be implemented as such.
As a side note, in the `v3` branch, non-public (or not yet implemented) parameters can now be set with a low-level, untyped `set(@NonNull String name, Object value)` method. For public parameters, typed accessors are also available and, of course, encouraged.

**Comment by clement-leprovost-algolia** [comment]
Superseded by #66.
