### ISSUE TITLE
java.lang.RuntimeException: An error occured while executing doInBackground()

### ISSUE THREAD

**Issue by RobertoIDL** [algolia/algoliasearch-client-android#8]
Hi,

I've noticed that our application is getting a few crashes inside your library. I have the stack trace of the problem just in case this may help you find the source of the problem.

0java.lang.RuntimeException: An error occured while executing doInBackground()
1	at android.os.AsyncTask$3.done(AsyncTask.java:200)
2	at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:274)
3	at java.util.concurrent.FutureTask.setException(FutureTask.java:125)
4	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:308)
5	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
6	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
7	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
8	at java.lang.Thread.run(Thread.java:1019)
9Caused by: java.lang.IllegalStateException: Adapter is detached.
10	at org.apache.http.impl.conn.AbstractPooledConnAdapter.assertAttached(AbstractPooledConnAdapter.java:90)
11	at org.apache.http.impl.conn.AbstractPooledConnAdapter.open(AbstractPooledConnAdapter.java:118)
12	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:536)
13	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
14	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
15	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)
16	at com.algolia.search.saas.APIClient._request(APIClient.java:593)
17	at com.algolia.search.saas.APIClient.getRequest(APIClient.java:495)
18	at com.algolia.search.saas.Index.search(Index.java:619)
19	at com.algolia.search.saas.Index$ASyncIndexTask.doInBackground(Index.java:1180)
20	at com.algolia.search.saas.Index$ASyncIndexTask.doInBackground(Index.java:972)
21	at android.os.AsyncTask$2.call(AsyncTask.java:185)
22	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:306)

This has happened in a few Samsung devices so far.

Hope it helps.

Regards,

R.

**Comment by Nagriar** [comment]
Hi @RobertoIDL,

Could you give me the version of the API client?

Thanks,

**Comment by RobertoIDL** [comment]
Hi @Nagriar 

The version is:  1.6.3

R.

**Comment by RobertoIDL** [comment]
And more:

0java.lang.RuntimeException: An error occured while executing doInBackground()
1	at android.os.AsyncTask$3.done(AsyncTask.java:200)
2	at java.util.concurrent.FutureTask$Sync.innerSetException(FutureTask.java:274)
3	at java.util.concurrent.FutureTask.setException(FutureTask.java:125)
4	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:308)
5	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
6	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
7	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
8	at java.lang.Thread.run(Thread.java:1027)
9Caused by: java.lang.NullPointerException
10	at org.apache.http.impl.conn.SingleClientConnManager.revokeConnection(SingleClientConnManager.java:373)
11	at org.apache.http.impl.conn.SingleClientConnManager.getConnection(SingleClientConnManager.java:218)
12	at org.apache.http.impl.conn.SingleClientConnManager$1.getConnection(SingleClientConnManager.java:189)
13	at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:325)
14	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:555)
15	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:487)
16	at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:465)
17	at com.algolia.search.saas.APIClient._request(APIClient.java:593)
18	at com.algolia.search.saas.APIClient.getRequest(APIClient.java:495)
19	at com.algolia.search.saas.Index.search(Index.java:619)
20	at com.algolia.search.saas.Index$ASyncIndexTask.doInBackground(Index.java:1180)
21	at com.algolia.search.saas.Index$ASyncIndexTask.doInBackground(Index.java:972)
22	at android.os.AsyncTask$2.call(AsyncTask.java:185)
23	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:306)

**Comment by Nagriar** [comment]
I released the version 1.6.5 that fixes the concurrency issue in the method _request. 

Let me know if you still have the issue with this version.

**Comment by RobertoIDL** [comment]
Thanks @Nagriar 

Can you please add the jar into this directory?

https://github.com/algolia/algoliasearch-client-android/tree/master/dist

Regards.

**Comment by Nagriar** [comment]
Oh yes sorry, it's good now: https://github.com/algolia/algoliasearch-client-android/blob/master/dist/algoliasearch-client-android-1.6.5.jar

**Comment by RobertoIDL** [comment]
Thanks, project updated.

I'll have to wait until next release to see the impact. 

Regards.

**Comment by dethi** [comment]
Can I close the issue?

**Comment by Nagriar** [comment]
Yes
