### ISSUE TITLE
SNI fixes/support

### ISSUE THREAD

**Issue by redox** [algolia/algoliasearch-client-android#9]
Check http://blog.dev001.net/post/67082904181/android-using-sni-and-tlsv1-2-with-apache

**Comment by asurak** [comment]
What was the thing about using a different library for the test and different for the actual deployment?

**Comment by redox** [comment]
We need to package the API client as an APK + test it using very-Android-specific travis build; but I didn't manage to make it work last time I tried.

**Comment by vvo** [comment]
saucelabs has https://saucelabs.com/appium to test on real devices I dunno if that could help. So we could do a fake empty application and then test it in saucelabs?
